# This is a basic workflow to help you get started with Action

name: Sync tieraid app
permissions:
  contents: read
# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions 
  workflow_dispatch:
  
  repository_dispatch:
    types: [sync]

# A workflow run is made up of one or more jobs that can run s
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        env:
            BACKEND: https://tieraid.be
        # Steps represent a sequence of tasks that will be exe
        steps:
            # Checks-out your repository under $GITHUB_WORKSPA
            - name: Clone github pages of root tieraid
              uses: actions/checkout@v4
              with:
                repository: tieraid-app/tieraid-app-frontend
                ref: main
                ssh-key: ${{ secrets.CLONE_FRONTEND_KEY }}

            - name: Fetch tenant information
              id: tenant
              uses: fjogeleit/http-request-action@v1
              with:
                url: ${{ env.BACKEND }}/info/
                method: 'GET'

            - name: Setup environment variables
              run: |
                  cat << EOF > .env
                  VITE_BACKEND_URL=${{ env.BACKEND }}
                  VITE_WEBSITE_NAME=${{fromJson(steps.tenant.o
                  EOF

            - name: Setup for tieraid
              run: |
                  mv index-tieraid.html index.html

            # Runs a single command using the runners shell
            - name: Install dependencies
              run: |
                  npm ci

            - name: Test and build
              run: |
                  npm test
                  npm run build

            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v4
              with:
                target_branch: gh-pages
                build_dir: dist
                fqdn: www.tieraid.app
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
